#!/bin/bash
set -e

readonly HOSTNAME=$(hostname -f)

readonly ERLANGCOOKIEFILE="${EJABBERD_ROOT}/.erlang.cookie"
readonly EJABBERDCTL="${EJABBERD_ROOT}/bin/ejabberdctl"
readonly CONFIGFILE="${EJABBERD_ROOT}/conf/ejabberd.yml"
readonly CONFIGTEMPLATE="${EJABBERD_ROOT}/conf/ejabberd.yml.tpl"
readonly CTLCONFIGFILE="${EJABBERD_ROOT}/conf/ejabberdctl.cfg"
readonly CTLCONFIGTEMPLATE="${EJABBERD_ROOT}/conf/ejabberdctl.cfg.tpl"
readonly SSLCERTHOST="${EJABBERD_ROOT}/ssl/host.pem"
readonly SSLCERTDOMAIN="${EJABBERD_ROOT}/ssl/xmpp_domain.pem"
readonly LOGDIR="${EJABBERD_ROOT}/logs"

readonly PYTHON_JINJA2="import os;
import sys;
import jinja2;
sys.stdout.write(
    jinja2.Template
        (sys.stdin.read()
    ).render(env=os.environ))
"""


is_set() {
    local var=$1

    [[ -n $var ]]
}


file_exist() {
    local file=$1

    [[ -e $file ]]
}


is_true() {
    local var=${1,,}
    local choices=("yes" "1" "y" "true")
    for ((i=0;i < ${#choices[@]};i++)) {
        [[ "${choices[i]}" == $var ]] && return 0
    }
    return 1
}


make_snakeoil_certificate() {
    local domain=$1
    local certfile=$2

    openssl req -subj "/CN=${domain}" \
                -new \
                -newkey rsa:2048 \
                -days 365 \
                -nodes \
                -x509 \
                -keyout /tmp/selfsigned.key \
                -out /tmp/selfsigned.crt

    echo "Writing ssl cert and private key to '${certfile}'..."
    cat /tmp/selfsigned.crt /tmp/selfsigned.key > ${certfile}
    rm /tmp/selfsigned.crt /tmp/selfsigned.key
}


make_host_snakeoil_certificate() {
    local domain='localhost'

    is_true ${ERLANG_NODE} \
      && domain=${HOSTNAME}

    echo -n "Missing ssl cert for your host. "
    echo "Generating snakeoil ssl cert for ${domain}..."

    make_snakeoil_certificate ${domain} ${SSLCERTHOST}
}


make_domain_snakeoil_certificate() {
    local domain='localhost'

    is_set ${XMPP_DOMAIN} \
      && domain=${XMPP_DOMAIN}

    echo -n "Missing ssl cert for your xmpp domain. "
    echo "Generating snakeoil ssl cert for ${domain}..."

    make_snakeoil_certificate ${domain} ${SSLCERTDOMAIN}
}


make_config() {
    echo "Generating ejabberd config file..."
    cat ${CONFIGTEMPLATE} \
      | python -c "${PYTHON_JINJA2}" \
      > ${CONFIGFILE}

    echo "Generating ejabberdctl config file..."
    cat ${CTLCONFIGTEMPLATE} \
      | python -c "${PYTHON_JINJA2}" \
      > ${CTLCONFIGFILE}
}


set_erlang_cookie() {
    echo "Set erlang cookie to ${ERLANG_COOKIE}..."
    echo ${ERLANG_COOKIE} > ${ERLANGCOOKIEFILE}
    chmod 400 ${ERLANGCOOKIEFILE}
}


ctl() {
    local action="$1"
    ${EJABBERDCTL} ${action} >/dev/null
}


_trap() {
    echo "Stopping ejabberd..."
    if ctl stop ; then
        local cnt=0
        sleep 1
        while ctl status || test $? = 1 ; do
            cnt=`expr $cnt + 1`
            if [ $cnt -ge 60 ] ; then
                break
            fi
            sleep 1
        done
    fi
}


## setup

# if ERLANG_NODE is true reset it to "ejabberd" and let erlang
# add hostname to the node. This is for backward compatibility.
is_true ${ERLANG_NODE} \
  && export ERLANG_NODE="ejabberd"

# generate config file
make_config

# set erlang cookie if ERLANG_COOKIE is set
is_set ${ERLANG_COOKIE} \
  && set_erlang_cookie

# generate host ssl cert if missing
file_exist ${SSLCERT_DOMAIN} \
  || make_host_snakeoil_certificate

# generate xmmp domain ssl cert if missing
file_exist ${SSLCERT_HOST} \
  || make_domain_snakeoil_certificate

# Catch signals and shutdown ejabberd
trap _trap SIGTERM SIGINT

## run ejabberd
case "$@" in
    start)
        tail -F ${LOGDIR}/crash.log \
                ${LOGDIR}/error.log \
                ${LOGDIR}/erlang.log &
        echo "Starting ejabberd..."
        exec ${EJABBERDCTL} "live" &
        child=$!
        wait $child
    ;;
    live)
        echo "Starting ejabberd in 'live' mode..."
        exec ${EJABBERDCTL} "live"
    ;;
esac
